version: '3.8'
services:
  api:
    build:
      dockerfile: Dockerfile
      context: "./server"
    container_name: server_backend
    ports:
      - '3031:3031'
    volumes:
      - ./server:/app
      - ./app/node_modules

  client:
    build:
      dockerfile: Dockerfile
      context: ./client
    container_name: client_frontend
    stdin_open: true
    tty: true
    ports:
      - '5173:5173'
    volumes:
      - ./client:/app
      - ./app/node_modules