version: '3.8'
services:
  api:
    build: ./api
    container_name: api_backend
    ports:
      - '3031:3031'
    volumes:
      - ./api:/app
      - ./app/node_modules
  client:
    build: ./client
    container_name: client_frontend
    ports:
      - '5173:5173'
    volumes:
      - ./client:/app
      - ./app/node_modules
    stdin_open: true
    tty: true