version: '3.8'
services:
  vite-client:
    build:
      dockerfile: Dockerfile
      context: ./vite-client
    container_name: vite-client
    stdin_open: true
    tty: true
    ports:
      - '443:443'
    volumes:
      - ./vite-client:/app
      - /app/node_modules

  server_backend:
    build:
      dockerfile: Dockerfile
      context: ./server
    container_name: server_backend
    ports:
      - '3031:3031'
    volumes:
      - ./server:/app
      - /app/node_modules